### ISSUE TITLE
Command 'DBML: To SQL' resulted in an error (Expected "{", comment, or whitespace but "S" found.)

### ISSUE THREAD

**Issue by mithunkundu1983** [mattmeyers/vscode-dbml#10]
My DBML file
Project Enterprise Search {
	database_type: 'mysql'
	note: 'DB schema for Enterprise Search'
}

Table Org{
  id varchar(36) [pk]
	name varchar [not null]
}

Table OrgOptionsDetails{
  id int [pk, increment]
	name varchar(32) [not null]
	description varchar(1024) [not null]
  example varchar(256) [not null]
  dataType varchar(24) [not null]
  subType varchar(24)
  dataList varchar
  default varchar(256)
  required boolean [default: false]
  readOnly boolean [default: false]
  enableOn int
  enableValue varchar(256)
  validation varchar(256)
}

Table OrgOptions{
  id int [pk, increment]
	org_id int [ref: > Org.id]
	org_opt_id int [ref: > OrgOptionsDetails.id]
  value varchar [not null]
}

Table Index{
  id varchar(36) [pk]
	name varchar [not null]
	org_id int [ref: > Org.id]
	crawler_type_id int [ref: > CrawlerTypes.id]
}

Table IndexOptionsDetails{
  id int [pk, increment]
	name varchar(32) [not null]
	description varchar(1024) [not null]
  example varchar(256) [not null]
  dataType varchar(24) [not null]
  subType varchar(24)
  dataList varchar
  default varchar(256)
  required boolean [default: false]
  readOnly boolean [default: false]
  enableOn int
  enableValue varchar(256)
  validation varchar(256)
}

Table IndexOptions{
  id int [pk, increment]
	index_id varchar(36) [ref: > Index.id]
	index_opt_id int [ref: > IndexOptionsDetails.id]
  value varchar [not null]
}

Table SortOptions{
  id int [pk, increment]
  index_id varchar(36) [ref: > Index.id]
	name varchar [not null]
}

Table SearchUser{
  id varchar [not null, unique]
  org_id varchar(36) [ref: > Org.id]
}

Table Query{
  id varchar(36) [pk]
  user_id int [not null, unique, ref: > SearchUser.id]
  org_id int [not null, unique, ref: > Org.id]
  queryType varchar [not null]
  queryText carchar [not null]
  created_at datetime [default: `now()`]
}

Table QueryIndexMapping{
  query_id int [not null, unique, ref: > Query.id]
  index_id int [not null, unique, ref: > Index.id]
}

Table Document{
  id varchar(36) [pk]
  fileDataType varchar [not null]
  storageid varchar(36) [not null, unique]
}

Table DocumentIndexMapper{
  doc_id varchar(36) [ref: > Document.id]
  index_id varchar(36) [ref: > Index.id]
}

Table CrawlerOptionsDetails{
  id int [pk, increment]
	name varchar(32) [not null]
	description varchar(1024) [not null]
  example varchar(256) [not null]
  data_type varchar(24) [not null]
  sub_type varchar(24)
  data_list varchar
  default_value varchar(256)
  required boolean [default: false]
  readOnly boolean [default: false]
  enableOn int
  enableValue varchar(256)
  validation varchar(256)
}

Table CrawlerOptions{
  id int [pk, increment]
	index_id varchar(36) [ref: > Index.id]
	crawler_opt_detail_id int [ref: > CrawlerOptionsDetails.id]
	crawler_type_id int [ref: > CrawlerTypes.id]
  value varchar [not null]
}

Table CrawlerTypes{
  id varchar(36) [pk]
	type varchar(36) [not null]
}

Table CrawlerReg{
  id varchar(16) [pk]
	uri varchar [not null]
	crawler_type_id int [ref: > CrawlerTypes.id]
	crawler_polls boolean [default: false]
	downLoad_enabled boolean [default: true]
}

Table CrawlerOrgs{
  crawler_reg_id varchar(16) [ref: > CrawlerReg.id]
  org_id int [ref: > Org.id]
}

Table CrawlerIndexes{
  crawler_reg_id varchar(16) [ref: > CrawlerReg.id]
  index_id int [ref: > Index.id]
}

Table CrawlerReq{
  id varchar(16) [pk]
  crawler_reg_id varchar(16) [ref: > CrawlerReg.id]
  created_at datetime
  comp_at datetime
  timeout_ms int
  completed boolean [default: false]
}

Table CrawlerReqIndexes{
  crawler_req_id varchar(16) [ref: > CrawlerReq.id]
  index_id int [ref: > Index.id]
  index_update_id int [ref: > IndexUpdate.id]
}

Table CrawledDocs{
  path varchar
  index_id varchar(36) [ref: > Index.id]
  doc_id varchar(36) [ref: > Document.id]
  file_type_id int [ref: > FileType.id]
  crawler_req_id varchar(16) [ref: > CrawlerReq.id]
  user varchar(16)
  last_crawled_at datetime
  op_pending varchar(8) [note: 'add , update, delete, index, none']
  error varchar(36)
}

Table FileType{
  id int
  name varchar(32)
}

enum index_op_status {
    pending
    doc_list_req
    doc_list_rec
    doc_list_failed
    crawl_progress
    crawl_partial_failed
    crawl_failed
    complete
}

Table IndexUpdate{
  id int [pk, increment]
  index_id int [ref: > Index.id]
  operation int [note: '0 for Rebuild Index, 1 for Update Index']
  completed boolean [default: false]
  req_time datetime
  comp_time datetime
  status index_op_status
}

**Comment by mattmeyers** [comment]
This error is a DBML syntax error. The project name cannot contain spaces unless wrapped in double quotes. Therefore change  `Enterprise Search` to `"Enterprise Search"`. 

<strike>You have another syntax error in the default value of the created_at column of the Query table. `now()` is a function and needs to be wrapped in backticks i.e. change `now()` to `` `now()` ``.</strike>

EDIT: Disregard this comment about the now() function. The backticks got lost when I copied the code.
