### ISSUE TITLE
DBML: to SQL not working

### ISSUE THREAD

**Issue by aisbergde** [mattmeyers/vscode-dbml#16]
I used the sample code from https://dbdiagram.io/d
then I tried "to SQL" with target MS SQL Server, but I only get errors:
![image](https://user-images.githubusercontent.com/9020187/109080920-ad3c1280-7701-11eb-8dae-4951248b1895.png)

VSC:

```
Version: 1.53.2 (user setup)
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:48:04.245Z
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19041
```

**Comment by mattmeyers** [comment]
Hey, thanks for bringing this to my attention. It looks like this is probably due to an addition to the language that the current dbml parser can't handle. I'll bump the version of the dbml parser and release a new version of the extension this weekend.

**Comment by mattmeyers** [comment]
Hi @aisbergde, I updated the dependencies and this seems to have fixed the issue. Please update your extension to see the fix.
