### ISSUE TITLE
DBML: To SQL' resulted in an error

### ISSUE THREAD

**Issue by mithunkundu1983** [mattmeyers/vscode-dbml#9]
Command 'DBML: To SQL' resulted in an error (Expected Table Group, comment, end of input, enum, references, table, or whitespace but "P" found.)

**Comment by mattmeyers** [comment]
I suspect the DBML file you are editing contains a Project declaration. I have updated the DBML core library version to handle projects. Please update to v0.3.3 of the plugin for this functionality.

**Comment by mithunkundu1983** [comment]
Thanks a lot for prompt action.
